### ISSUE TITLE
Race Condition in sending Webhooks

### ISSUE THREAD

**Issue by huwaireb** [GoUAE/Hummus#1]
Currently when piping the whatsapp message to discord we're using a Go routine.
https://github.com/GoUAE/Hummus/blob/0cc1a04e838e4ecaa08b2b514a77bca138ca949e/internal/whatsapp/whatsapp.go#L33

This is fine per say, as we need to process the messages concurrently, however at the same time the messages arrive at different times than expected, the ones that process (e.g no attachment) faster will be sent earlier causing a race condition.

### Suggested Solution
Applying a mutex would probably solve this.

However, it might require the PipeToDiscord function to be refactored more in order to be more granular to account for this.

cc @Gaurav-Gosain

**Comment by Gaurav-Gosain** [comment]
Closing in favor of fixes done in #2
